version: "3.8"

services:
  app:
    build: .
    container_name: stable_whisper_api
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads  # Persist uploaded files
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped
